runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /templates
  script: templates
- url: /styles
  script: styles
- url: /scripts
  script: scripts
- url: /media
  script: media
- url: /.*
  script: main.app
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
